default: &default
#  secret_key_base: "f409e873105bfa98184af56cd8b12c181aae4e02706c036424d026476f863541e69c53e22443813ef7e5935ee11b272d82244b626c799d4acf45e45f0ece79b4"
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_key_base: "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"
  email: email@example.com

  recaptcha_public_key: "6LeQYhoTAAAAAH8LIepPPCY3HUPrTmJmA9tIK0EV"
  recaptcha_private_key: "6LeQYhoTAAAAACoEFmlHt2UVgdw35k5fD2oOB3gH"

test:
  <<: *default
  secret_key_base: "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"
  email: email@example.com
  census_url: "https://fake.url"

staging:
  server_name: ""
  <<: *default

production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  census_api_end_point: <%= ENV["KEY_census_api_end_point"] %>
  census_api_institution_code: <%= ENV["KEY_census_api_institution_code"] %>
  census_api_portal_name: <%= ENV["KEY_census_api_portal_name"] %>
  census_api_user_code: <%= ENV["KEY_census_api_user_code"] %>

  sms_end_point:  <%= ENV["KEY_sms_end_point"] %>
  sms_username: <%= ENV["KEY_sms_username"] %>
  sms_password: <%= ENV["KEY_sms_password"] %>

  http_basic_username: <%= ENV["KEY_http_basic_username"] %>
  http_basic_password: <%= ENV["KEY_http_basic_password"] %>

  twitter_key: <%= ENV["TW_Consumer_key"] %>
  twitter_secret: <%= ENV["TW_Consumer_secret"] %>
  facebook_key: <%= ENV["FB_App_id"] %>
  facebook_secret: <%= ENV["FB_App_secret"] %>
  google_oauth2_key: <%= ENV["KEY_google_oauth2_key"] %>
  google_oauth2_secret: <%= ENV["KEY_google_oauth2_secret"] %>

  translate_username: <%= ENV["KEY_translate_username"] %>
  translate_password:  <%= ENV["KEY_translate_password"] %>

  rollbar_server_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  #server_name: <%= ENV["KEY_server_name"] %>

preproduction:
  server_name: ""
  <<: *production
